#!/bin/bash
# CI build script for microblog
# Installs SVG renderer and builds Jekyll in production mode
# so social media thumbnails are auto-generated.
#
# Usage on Cloudflare Pages:
#   Set build command to: bash build.sh
#
# Usage on GitHub Actions (via .github/workflows/pages.yml):
#   bash build.sh --trace --baseurl "/my-repo"

set -e

echo ":: Installing SVG renderer for thumbnail generation (optional)..."
if apt-get update -qq 2>/dev/null && apt-get install -y -qq librsvg2-bin 2>/dev/null; then
  echo "    (using rsvg-convert)"
else
  echo "    (using Node.js resvg)"
fi

echo ":: Building Jekyll site (production)..."
JEKYLL_ENV=production bundle exec jekyll build "$@"

# Convert SVGs to PNGs for social media thumbnails
# If rsvg-convert wasn't installed, use the Node.js fallback
if ! command -v rsvg-convert &> /dev/null; then
  echo ":: Converting SVG thumbnails to PNG (Node.js)..."
  # Remove fallback PNGs generated by Jekyll plugins so resvg re-renders them
  rm -f assets/thumbnails/*.png
  node scripts/convert-thumbnails.mjs
fi

echo ":: Build complete"
